# Configuration SMTP pour l'envoi d'emails
# Ce fichier doit être placé dans src/main/resources/

# Serveur SMTP Gmail
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587

# Authentification
# Pour Gmail, vous devez utiliser un "Mot de passe d'application"
# ou activer "Accès moins sécurisé" (déconseillé)
mail.username=rfanomezaniavo@gmail.com
mail.password=ngjo eody zklq vxib

# Email expéditeur (généralement le même que username)
mail.from=rfanomezaniavo@gmail.com

# Propriétés supplémentaires (optionnelles)
mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.smtp.ssl.trust=smtp.gmail.com
mail.smtp.connectiontimeout=5000
mail.smtp.timeout=5000
mail.smtp.writetimeout=5000